### ISSUE TITLE
Is it possible to compile it to 32bits?

### ISSUE THREAD

**Issue by eduardo4jesus** [conda-forge/hpp-fcl-feedstock#110]
### Comment:

Would there be anything preventing this library from being compiled into 32-bit architecture?

**Comment by jorisv** [comment]
Hello @eduardo4jesus,

Do you want a win-32 build or a linux-32 build ?
As I understand, [conda-forge doesn't support linux-32 build](https://github.com/conda-forge/conda-forge.github.io/issues/163)

**Comment by eduardo4jesus** [comment]
I need it for Windows 32 bits. Would it be possible to compile it without conda?

**Comment by jorisv** [comment]
Apparently, conda doesn't support the win-32 architecture anymore.

You can try to build it from source. Here some [instructions](https://github.com/humanoid-path-planner/hpp-fcl/blob/devel/INSTALL).

If you have issues to build it, open an issue on the hpp-fcl repository.
